# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9002
  servlet:
    context-path: /
spring:
  application:
    name: "@pom.artifactId@ - @pom.version@"
  # 环境 dev|test|prod
  profiles:
    active: test
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  servlet:
    multipart:
      max-file-size: 400MB
      max-request-size: 200MB
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  freemarker:
    check-template-location: false
  cache: 
    ehcache: 
      config: classpath:/ehcache/ehcache.xml
  datasource:
    url: jdbc:mysql://localhost:3306/zc_oauth?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&verifyServerCertificate=false
    username: zc
    password: Mydb2018
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    
###
password:
  algorithmName: md5
  hashIterations: 2